services:
	- type: web
		name: playwright-firefox-scraper
		env: python
		plan: standard 
		buildCommand: |
			pip install --upgrade pip
			pip install -r requirements.txt
			#PlaywrightのCLIを使い、FirefoxブラウザとOSの依存関係をインストール
			python -m playwright install --with-deps firefox
		startCommand: "uvicorn main:app --host 0.0.0.0 --port 80"
		disks:
			- name: cookie-storage
				mountPath: /data
				sizeGB: 1
		healthCheckPath: /

